### ISSUE TITLE
Run genn_proto.bat error

### ISSUE THREAD

**Issue by Solomon1588** [neopenx/Dragon#1]
Hello,I saw your blog and try to study this project.
However,when I followed the step 8 to compile the project in win10 ,after running gen_proto.bat, the terminal showed errors:
**'R' is not internal or external command**.
And then I tried to retype the raw scripts into a new .bat  file and it worked well.
So I think there are some illegal charaters in your bat file such as:
**echo ——————————————————————————————————**
Best wishes,
Solomon

**Comment by neopenx** [comment]
Thanks. 
If you re-open it with wordpad.exe and save it but not notepad.exe，it could work also.
I edited this .bat file in UNIX OS(Linux) before, and the CMD's parser seems works as notepad.exe
and can not parse 'newline' char(\n)

**Comment by tomicfish** [comment]
请问下你的Dragon第三方库有没有试过用交叉编译，我用Dragon交叉编译的时候（我屏蔽了CUDA，想只用CPU版本，在CMakeLists.txt里涉及到的都注释掉了），然后在cmake-gui里配置好交叉工具链后，config后出现Error in configuration process, project files maybe invali. 报错的三个编译选项是：CMAKE_BUILD_TYPE、CMAKE_CONFIGURATION_TYPES、CMAKE_FIND_ROOT_PATH，编译环境：Ubuntu 14.04 cmake：2.8.12.2
