### ISSUE TITLE
TensorFlow documentation copyright issue

### ISSUE THREAD

**Issue by thinxer** [neopenx/Dragon#3]
In `dragon.vm.tensorflow`, there are many documentation apparently copied from TensorFlow. For example, the documentation of [`matmul`](https://github.com/neopenx/Dragon/blob/990c496bc653c30d26a63df97c15ef2206745421/Dragon/python/vm/tensorflow/ops/math_ops.py#L42) is exactly the same as [`tf.matmul`](https://www.tensorflow.org/api_docs/python/tf/matmul). 

However, the copyright header shows `Copyright(c) 2017 SeetaTech`, which is not compatible with the [TensorFlow License](https://github.com/tensorflow/tensorflow/blob/master/LICENSE).

**Comment by PhyscalX** [comment]
Thanks, we will remove these documentation soon.
Currently，our team(actually just me) are busy on both coding and documenting.(:->)
