### ISSUE TITLE
Is there original code commited by neopenx at Mar 2, 2016

### ISSUE THREAD

**Issue by ForeverDJ-ux** [neopenx/Dragon#4]
Anybody has this original code ?
my email address: dj1993@mail.ustc.edu.cn
thanks!

**Comment by PhyscalX** [comment]
Dragon 0.1 was removed due to enormous potential bugs and poor designing of architecture.
If you still want to refer it,  download from https://pan.baidu.com/s/1slRVTzn.

**Comment by ForeverDJ-ux** [comment]
I got it, thanks!
