### ISSUE TITLE
Error in PrintOptimizedGraph

### ISSUE THREAD

**Issue by liujshi** [neopenx/Dragon#6]
Hello， i‘m trying to understand the frame.
in python3.5. unicode and byte problems still occur, I uncomment the PrintOptimizedGraph method in workspace.py， then run solve_quick.py in cifar10 example.
![image](https://user-images.githubusercontent.com/4653865/29071771-95d55bca-7c77-11e7-8e37-933081748959.png)

**Comment by PhyscalX** [comment]
oops~
I used ``#define PyBytes_FromStringAndSize PyUnicode_FromStringAndSize`` to remove 'b'  prefix  for a readable str in Python3, but forgot that protobuf requires a bytes.

Our new solution is to add a ``StdStringToPyUnicode`` in Dragon/modules/python/dragon.h, 
which is used to return a readable string, while keep ``StdStringToPyBytes`` for passing a protobuf serialized string(Unicode can't accept this format) to the frontend.
