### ISSUE TITLE
error with CUDA

### ISSUE THREAD

**Issue by bin913** [neopenx/Dragon#7]
Ubuntu 16.04.3 LTS, cuda8.0, cudnn6.0

FATAL conv_op.h:54] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs 0) CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace : ***
Aborted (core dumped)

**Comment by Spark001** [comment]
Which version/date of Dragon do you use ?
In latest version, line 54 in conv_op.h isn't a cudnn check.

**Comment by bin913** [comment]
The project  name is CC-Dragon,and i can't find more version information.  In this version, the cudnn check as follows
line 52:               CUDNN_CHECK(cudnnSetConvolution2dDescriptor(conv_desc,
line 53:                        this->pad[0], this->pad[1], this->stride[0], this->stride[1],
line 54:                       1, 1, CUDNN_CROSS_CORRELATION));

**Comment by PhyscalX** [comment]
_CC-Dragon_ is used for VALSE2017 DEMO ONLY，and cuDNN v6 had not been released during that time. As we all know, NVIDIA refactors the convolution module for the dilation(atrous) in v6.

Please clone the latest Dragon, it is compatible with CUDA 7/8/9，and cuDNN v4/v5/v6/v7.
BTW，the pure C API has not been finished yet. You can not use the latest Dragon to deploy your models.

**Comment by bin913** [comment]
Thank you very much!  I will use the latest Dragon.
